services:
  mordor-2.0:
    image: mordor-2.0:latest
    hostname: mordor-2.0
    container_name: mordor-2.0
    restart: always
    volumes:
      - ./app:/app
      - ./db:/data
    build:
      context: ./app
      dockerfile: Dockerfile
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    ports:
      - "8081:8080"
    environment:
      DATABASE_URL: sqlite:///data/db/database.db