services:
  mordor-2.0:
    image: mordor-2.0:latest
    hostname: mordor-2.0
    container_name: mordor-2.0
    restart: always
    volumes:
      - ./app:/app
      - ./db:/db
    build:
      context: ./app
      dockerfile: Dockerfile
    command: ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8081", "--reload"]
    ports:
      - "8081:8081"
    environment:
      UPLOAD_DIR: /db/data/uploads
      DATABASE_URL: sqlite:///db/data/database.db
      CHROMA_SERVER: http://chromadb:8000
      # OAuth Configuration
      ISSUER : http://localhost:8080/realms/Mordor-2.0
      CLIENT_ID : TestClientSecret
      CLIENT_SECRET : g8rTPq20CQEWV3xODDX4jHYZe5qa1BY8

    depends_on:
      - chromadb
    networks:
      - app_network

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    hostname: chromadb
    restart: always
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
    volumes:
      - ./Embeddings/chroma_data:/chroma
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    external : true