services:
  mordor-2.0:
    image: mordor-2.0:latest
    hostname: mordor-2.0
    container_name: mordor-2.0
    restart: always
    volumes:
      - ./app:/app
      - ./db:/db
    build:
      context: ./app
      dockerfile: Dockerfile
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    ports:
      - "8081:8080"
    environment:
      DATABASE_URL: sqlite:///db/data/database.db
      CHROMA_SERVER: http://chromadb:8000
    depends_on:
      - chromadb
    networks:
      - app_network

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    hostname: chromadb
    restart: always
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
    volumes:
      - chroma_data:/chroma
    networks:
      - app_network

volumes:
  chroma_data:
  db:  # This was implicitly created by your original volume mount

networks:
  app_network:
    driver: bridge
